### ISSUE TITLE
Encounter no able to compile

### ISSUE THREAD

**Issue by xuncoder** [biessek/flutter_country_picker#4]
Hi, I have encounter the issues when I compile my program with your plugin
e: C:\Users\user\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_country_picker-0.1.0\android\src\main\kotlin\rocks\biessek\fluttercountrypicker\FlutterCountryPickerPlugin.kt: (26, 46): Type inference failed. Expected type mismatch: inferred type is ArrayList<String>? but ArrayList<String> was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_country_picker:compileDebugKotlin'.
> Compilation error. See log for more details

The gradle version I used is 'com.android.tools.build:gradle:3.1.2' without set other kotlin plug. 

Below logic is how I used your country picker plugin:
Widget countryField(){

    if (_isChangeInfo == true ) {

    Widget countryMenuList = new Container(
     child: new Row(
        children: <Widget>[
          CountryPicker(
            onChanged: (Country country) {
              setState(() {
                _selected = country;
                _countryName=country.name;
              });
            },
            selectedCountry: _selected,
          ),
          Text(_countryName, style: new TextStyle(color: Colors.black, fontSize: 16.00),),
        ],
      )
    );

**Comment by biessek** [comment]
I've just uploaded 0.1.1. Please upgrade it when available to check if the error persists

**Comment by xuncoder** [comment]
It worked after upgrade to 0.1.1. Thanks for upgrade
